### PR TITLE
Python Script link is broken in https://docs.microsoft.com/en-us/samples/azure-samples/jmeter-aci-terraform/jmeter-aci-terraform/?source=docs

### LINKED ISSUE #52: Python Script link is broken in https://docs.microsoft.com/en-us/samples/azure-samples/jmeter-aci-terraform/jmeter-aci-terraform/?source=docs
When we click on python script link in https://docs.microsoft.com/en-us/samples/azure-samples/jmeter-aci-terraform/jmeter-aci-terraform/?source=docs 404 is coming.

This is fixed by PR https://github.com/Azure-Samples/jmeter-aci-terraform/pull/51

### PR DESCRIPTION
**Pull request by lakshaykaushik**
Python Script link is broken in the document:

https://docs.microsoft.com/en-us/samples/azure-samples/jmeter-aci-terraform/jmeter-aci-terraform/?source=docs

Fixing the link.

fixes #52

### CODE REVIEW

**Comment by lakshaykaushik** [comment]
This PR aims to close issue https://github.com/Azure-Samples/jmeter-aci-terraform/issues/52

**Comment by allantargino** [comment]
Hi @lakshaykaushik!
Thanks for the issue and the PR - but I can't reproduce the broken link.
When I navigate to the mentioned doc on `main`, the link works for me:

image

The relative link translates to: https://github.com/Azure-Samples/jmeter-aci-terraform/blob/main/scripts/jtl_junit_converter.py

**Comment by lakshaykaushik** [comment]
Hey Allan, this works fine when user goes to the link via github, but when user goes via https://docs.microsoft.com/en-us/samples/azure-samples/jmeter-aci-terraform/jmeter-aci-terraform/?source=docs , the link seems to be broken. 
Let me know if you are able to observe this.

**Review by allantargino — APPROVED** [review]

**Comment by allantargino** [comment]
LGTM, thanks @lakshaykaushik

**Pull request merged**
